name: Java CI

on:
  workflow_dispatch:

jobs:
  java_build:
    strategy:
      matrix:
        java_version: [ 8 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          lfs: 'true'
          java-version: ${{ matrix.java_version }}
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
      - name: Build with JDK ${{ matrix.java_version }}
        run: mvn -U -B deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

  compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: License Compliance
        run: mvn -U -P compliance org.honton.chas:license-maven-plugin:compliance