on:
  workflow_dispatch:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    branches:
      - main

jobs:
  pr-bot:
    runs-on: ubuntu-latest
    steps:
      - name: PR Bot
        uses: langchain4j/pr-bot@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
